import os
import sys
import copy
import platform
import awtk_config as config

BIN_DIR = os.environ['BIN_DIR']
LIB_DIR = os.environ['LIB_DIR']
TOOLS_NAME = os.environ['TOOLS_NAME']

env = DefaultEnvironment().Clone()
config.setEnvSpawn(env)

TK_SOURCES = Glob('tkc/*.c') + Glob('platforms/pc/*.c')
env.Library(os.path.join(LIB_DIR, 'tkc_core'), TK_SOURCES, LIBS=[])

TKC_DEPS_LIBS = config.TKC_STATIC_LIBS +  ['SDL2', 'glad'] + config.OS_LIBS
TKC_LINKFLAGS= env['LINKFLAGS'] + config.genDllLinkFlags(config.TKC_STATIC_LIBS, 'tkc')

env.SharedLibrary(os.path.join(BIN_DIR, 'tkc'), [],
                  LIBS=TKC_DEPS_LIBS, LINKFLAGS=TKC_LINKFLAGS)
